### ISSUE TITLE
result too bad

### ISSUE THREAD

**Issue by 11721206** [introlab/odas#156]
hello, thanks for this great projects.
I configure my projects files as follows:
[my_respeaker_4_mic_array.txt](https://github.com/introlab/odas/files/3211400/my_respeaker_4_mic_array.txt)

and my microphone array is put as follows:
![mic_locations](https://user-images.githubusercontent.com/19368412/58242853-21ee5a00-7d82-11e9-8b0a-5af560ecaa6c.jpg)

but I get the result two bad.
my source is a frequency = 1000hz sine wave, the location is (0.1, 0 , 0.05)(cm).
but my result is too bad as follows.
[mic3.log](https://github.com/introlab/odas/files/3211405/mic3.log)

the test pcm is:

[mic3.txt](https://github.com/introlab/odas/files/3211410/mic3.txt)
 for uploading ,I changed mic3.pcm into mic3.txt.

any suggestions? thanks very much.

**Comment by FrancoisGrondin** [comment]
Hi there,

The reason why the system is not doing well is because you have a narrowband signal (a 1000 Hz sine wave), and ODAS relies on GCC-PHAT, which works only for broadband signals such as speech. Unless the 1000 Hz signal is your real target, I suggest you use a wideband white noise signal to test your system, which should work very well.

**Comment by 11721206** [comment]
> Hi there,
> 
> The reason why the system is not doing well is because you have a narrowband signal (a 1000 Hz sine wave), and ODAS relies on GCC-PHAT, which works only for broadband signals such as speech. Unless the 1000 Hz signal is your real target, I suggest you use a wideband white noise signal to test your system, which should work very well.

thank you for your reply
